import type { CSSProperties } from "react";

/** Co-located styles for the agent editor's Skills tab (from the design's SkillsTab). */
export const s = {
  wrap: { maxWidth: 680 } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
  } satisfies CSSProperties,
  h2: { fontSize: 16, fontWeight: 700 } satisfies CSSProperties,
  filter: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 7,
    padding: "5px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 200,
  } satisfies CSSProperties,
  filterInput: {
    flex: 1,
    fontSize: 12,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-muted)", marginBottom: 14 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  row: (attached: boolean, dragging: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 11,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: attached ? "var(--bg-hover)" : "var(--bg-elevated)",
    opacity: dragging ? 0.4 : attached ? 1 : 0.7,
  }),
  handle: (active: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    cursor: active ? "grab" : "default",
    visibility: active ? "visible" : "hidden",
    display: "inline-flex",
  }),
  name: { fontSize: 12.5, fontWeight: 600, flex: 1 } satisfies CSSProperties,
  typeChip: (color: string): CSSProperties => ({
    fontSize: 10.5,
    fontWeight: 600,
    color,
    background: color + "1a",
    padding: "1px 7px",
    borderRadius: 4,
  }),
  moveGroup: { display: "flex", gap: 2 } satisfies CSSProperties,
  moveBtn: (disabled: boolean): CSSProperties => ({
    background: "none",
    border: "none",
    padding: 2,
    display: "inline-flex",
    color: "var(--text-muted)",
    cursor: disabled ? "not-allowed" : "pointer",
    opacity: disabled ? 0.35 : 1,
  }),
  actions: { display: "flex", gap: 8, marginTop: 16 } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
