import type { CSSProperties } from "react";

/** Co-located styles for the shared Context docs editor. */
export const s = {
  wrap: { maxWidth: 720 } satisfies CSSProperties,
  filter: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    padding: "6px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    marginBottom: 12,
  } satisfies CSSProperties,
  filterInput: {
    flex: 1,
    fontSize: 12.5,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-muted)", marginBottom: 12 } satisfies CSSProperties,
  inherited: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
    padding: "8px 12px",
    borderRadius: 7,
    border: "1px dashed var(--border)",
    marginBottom: 12,
  } satisfies CSSProperties,
  error: { fontSize: 12.5, color: "var(--crit)", marginBottom: 12 } satisfies CSSProperties,
  groupHead: {
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    margin: "14px 0 6px",
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  row: (attached: boolean, dragging: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: attached ? "var(--bg-hover)" : "var(--bg-elevated)",
    opacity: dragging ? 0.4 : 1,
  }),
  handle: (active: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    cursor: active ? "grab" : "default",
    visibility: active ? "visible" : "hidden",
    display: "inline-flex",
  }),
  hidden: {
    position: "absolute",
    width: 1,
    height: 1,
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  path: { fontSize: 12.5, fontWeight: 600, flex: 1, wordBreak: "break-all" } satisfies CSSProperties,
  tokens: { fontSize: 12, color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,
  notFound: { fontSize: 12, color: "var(--warn)", whiteSpace: "nowrap" } satisfies CSSProperties,
  moveGroup: { display: "flex", gap: 2 } satisfies CSSProperties,
  moveBtn: (disabled: boolean): CSSProperties => ({
    background: "none",
    border: "none",
    padding: 2,
    display: "inline-flex",
    color: "var(--text-muted)",
    cursor: disabled ? "not-allowed" : "pointer",
    opacity: disabled ? 0.35 : 1,
  }),
  footer: { display: "flex", alignItems: "center", gap: 12, marginTop: 16 } satisfies CSSProperties,
  total: { fontSize: 13, fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)", padding: "8px 0" } satisfies CSSProperties,
} as const;
