import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { assemblePrompt } from '../src/prompt.js';

/**
 * AC-8 golden: the assembled review prompt is byte-identical to what the code
 * BEFORE the prompt-logging change produced. The fixture was generated by
 * running `assemblePrompt` from snapshot commit d17edf2
 * (`git show d17edf2:reviewer-core/src/prompt.ts`) on the inputs stored beside
 * each expectation; see `_provenance` in the fixture. Never regenerate it from
 * the current code.
 */

interface Golden {
  guard: string;
  cases: {
    name: string;
    input: Parameters<typeof assemblePrompt>[0];
    user: string;
    assembly: Record<string, string | null>;
  }[];
}

// A 100+ char run of `x` is stored as `<<x*N>>` to keep the fixture small.
const raw = readFileSync(fileURLToPath(new URL('./fixtures/prompt-golden.json', import.meta.url)), 'utf8').replace(
  /<<x\*(\d+)>>/g,
  (_m, n: string) => 'x'.repeat(Number(n)),
);
const golden = JSON.parse(raw) as Golden;

describe('assemblePrompt is byte-identical to the pre-change snapshot (AC-8)', () => {
  for (const c of golden.cases) {
    it(`${c.name}: messages (system + user) and the trace assembly`, () => {
      const out = assemblePrompt(c.input);
      const system = `${c.input.system}\n\n${golden.guard}`;
      expect(out.messages).toEqual([
        { role: 'system', content: system },
        { role: 'user', content: c.user },
      ]);
      expect(out.assembly).toEqual({ ...c.assembly, system, user: c.user });
    });

    // L05 AC-41: an empty `specs` is the same as an absent one — no section, same bytes.
    it(`${c.name}: specs: [] leaves the prompt byte-identical`, () => {
      const { specs: _drop, ...base } = c.input;
      const out = assemblePrompt({ ...base, specs: [] });
      expect(out).toEqual(assemblePrompt(base));
      expect(out.messages[1]!.content).not.toContain('## Project context');
      if (!c.input.specs?.length) expect(out.messages[1]!.content).toBe(c.user);
    });
  }
});
